apiVersion: v2
name: neuro-monitoring
description: Helm chart for NeuroSwarm Monitoring Stack
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
- name: prometheus
  version: "15.0.0"
  repository: "https://prometheus-community.github.io/helm-charts"
- name: grafana
  version: "6.0.0"
  repository: "https://grafana.github.io/helm-charts"
- name: jaeger
  version: "0.40.0"
  repository: "https://jaegertracing.github.io/helm-charts"