global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'neuro-gateway'
    static_configs:
      - targets: ['neuro-gateway:8080']
  - job_name: 'neuro-indexer'
    static_configs:
      - targets: ['neuro-indexer:8081']